// Types constant

export const GET_DATA = 'GET_DATA';
export const SHOW_LOADER = 'SHOW_LOADER'
export const HIDE_LOADER = 'HIDE_LOADER'
export const SET_POKEMONS = 'GET_POKEMONS'
export const CHANGE_SEARCH_VALUE = 'CHANGE_SEARCH_VALUE'
export const SET_CURRENT_POKEMONS = 'SET_CURRENT_POKEMONS'
export const GO_TO_POKEMON = 'GO_TO_POKEMON'
export const GET_POKEMON_INFO = "GET_POKEMON_INFO"
export const SHOW_PAGE_LOADER = "SHOW_PAGE_LOADER"
export const HIDE_PAGE_LOADER = "HIDE_PAGE_LOADER"
export const SHOW_SEARCH_ALERT = 'SHOW_SEARCH_ALERT'
export const HIDE_SEARCH_ALERT = 'HIDE_SEARCH_ALERT'
export const SHOW_SERVER_ALERT = 'SHOW_SERVER_ALERT'
export const HIDE_SERVER_ALERT = 'HIDE_SERVER_ALERT'
